### ISSUE TITLE
Modifying the _id of a doc in a map function will affect the emitted row.id

### ISSUE THREAD

**Issue by fiatjaf** [pouchdb/mapreduce#215]
And, conseqüently, the `row.doc` when `include_docs` is `true`.

**Comment by fiatjaf** [comment]
Just discovered [this hidden piece of documentation](https://wiki.apache.org/couchdb/Introduction_to_CouchDB_views#Linked_documents) which says that CouchDB supports almost this thing, almost as the same way. So now is it a feature or a bug?

**Comment by nolanlawson** [comment]
Nah, this is just a straight-up bug. We should either do a `clone()` of the document before the user can mess with it, or we need to document not to do that. :)

I would actually lean towards the latter, because performance profiling consistently shows that structured cloning is a huge drain on perf, and I can't imagine a lot of cases where users would absolutely need to modify the input document. (And if they need to, they can clone it themselves.)

**Comment by nolanlawson** [comment]
I think this is one of those "just don't do that" kind of things. I don't want us to have to do defensive structured cloning everywhere because it's a performance hit

closing as "wontfix"
